### ISSUE TITLE
Incorrect timestamps

### ISSUE THREAD

**Issue by danthony06** [swri-robotics/ensenso#3]
The camera provides timestamps for when it has presumably captured data. This data is fetched from the camera, stored in the PCL data, but then the ROS driver discards it in favor of the time when the messages are published. This causes issues when registering the data back to a world frame of reference, because there is some latency between grabbing the data and publishing it. Instead, the time when the data is collected should be used for the ROS messages.

**Comment by pjreed** [comment]
Fixed by #4.
